version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - github
registries:
  github:
    type: git
    url: https://github.com
    username: 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 # username doesn't matter
    password: ${{ Coding_good }}
